-- is null
SELECT ANIMAL_ID FROM ANIMAL_INS
WHERE NAME IS NULL

-- is not null
SELECT ANIMAL_ID FROM ANIMAL_INS
WHERE NAME IS NOT NULL

-- deal with null
SELECT ANIMAL_TYPE, IFNULL (NAME, "No name"), SEX_UPON_INTAKE FROM ANIMAL_INS