-- JOIN EXAMPLE2
SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS AS O
LEFT JOIN ANIMAL_INS AS I
ON O.ANIMAL_ID = I.ANIMAL_ID
WHERE I.ANIMAL_ID IS NULL

-- JOIN EXAMPLE2
SELECT I.ANIMAL_ID, I.NAME FROM ANIMAL_INS AS I
JOIN ANIMAL_OUTS AS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.DATETIME > O.DATETIME
ORDER BY I.DATETIME

-- JOIN EXAMPLE3
SELECT I.NAME, I.DATETIME
FROM ANIMAL_INS AS I
LEFT JOIN ANIMAL_OUTS AS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE O.ANIMAL_ID IS NULL
ORDER BY I.DATETIME ASC
LIMIT 3

-- JOIN EXMAPLE4
SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS AS I
LEFT JOIN ANIMAL_OUTS AS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE (I.SEX_UPON_INTAKE = "Intact Male" and O.SEX_UPON_OUTCOME = "Neutered Male") or (I.SEX_UPON_INTAKE = "Intact Female" and O.SEX_UPON_OUTCOME = "Spayed Female");

-- JOIN EXAMPLE5
SELECT MILK.CART_ID
FROM (
    SELECT CART_ID FROM CART_PRODUCTS
    WHERE NAME = 'Milk'
) AS MILK
JOIN (
    SELECT CART_ID FROM CART_PRODUCTS
    WHERE NAME = 'Yogurt'
) AS YOGURT
ON MILK.CART_ID = YOGURT.CART_ID
GROUP BY MILK.CART_ID
ORDER BY MILK.CART_ID