-- STRING EXAMPLE
SELECT ANIMAL_ID, NAME, SEX_UPON_INTAKE FROM ANIMAL_INS
WHERE NAME IN('Lucy', 'Ella', 'Pickle', 'Rogan', 'Sabrina', 'Mitty')

-- REGEXP_LIKE EXAMPLE
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS
WHERE REGEXP_LIKE(NAME, 'El|el') and ANIMAL_TYPE = 'Dog'
ORDER BY NAME

--